full = ../formal-thesis.pdf

formal:
	pdfunite Титульный_лист_ВКР_Ступников_А.С..pdf Задание_ВКР_Ступников_А.С..pdf Аннотация__ВКР_Ступников_А.С..pdf \
		../bachelor-thesis.pdf ВКР_Ступников_А_С.pdf

clean:
	rm -f full